name: Keep Alive Space

on:
  schedule:
    - cron: '*/4 * * * *' # Every 4 minutes
  workflow_dispatch:      # Allow manual runs

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Health Endpoint
        run: curl -s https://naagazz-interview-checker.hf.space/health
